"""Write the command reference in docs/commands from the CLI itself.

Each top-level command group gets one page (`docs/commands/issue.md`, …) listing every command
under it with its usage, description and options. Pages are fully generated: edit the help texts
in `src/acli_py/cli/`, then run this script. `--check` changes nothing and exits 1 when a page
is out of date, as the tests do.

    uv run python scripts/cli_docs.py [--check]
"""

from __future__ import annotations

import sys
from enum import Enum
from pathlib import Path
from typing import Any

import typer
from rich.text import Text

from acli_py.cli import app

ROOT = Path(__file__).resolve().parents[1]
PAGES = ROOT / "docs" / "commands"
HEADER = "<!-- Generated by scripts/cli_docs.py from the CLI's help texts: do not edit. -->"

# Typer's click objects, typed loosely: recent Typer versions bundle their own click.
Command = Any
Param = Any


def _plain(markup: str | None) -> str:
    return Text.from_markup(markup or "").plain.strip()


def _is_option(param: Param) -> bool:
    return param.param_type_name == "option"


def _metavar(param: Param) -> str:
    if param.is_flag or param.count:
        return ""
    choices = getattr(param.type, "choices", None)
    if choices:
        return "[" + "|".join(str(getattr(c, "value", c)) for c in choices) + "]"
    name = str(param.type.name).removesuffix(" range")
    return {"str": "TEXT", "int": "INTEGER", "path": "PATH"}.get(name, name).upper()


def _default(param: Param) -> str:
    if param.required:
        return "required"
    value = param.default
    if isinstance(value, Enum):
        value = value.value
    if value in (None, False, "", [], ()) or (_is_option(param) and param.multiple and not value):
        return ""
    if isinstance(value, Path):
        value = str(value)
    return f"`{value}`"


def _cell(text: str) -> str:
    return " ".join(text.split()).replace("|", "\\|")


def _help(command: Command) -> tuple[str, str]:
    """Return (description, examples) from a command's docstring-based help."""
    text = command.help or ""
    lines = text.strip().splitlines()
    examples: list[str] = []
    description: list[str] = []
    in_examples = False
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("[dim]"):
            in_examples = True
        if in_examples:
            examples.append(_plain(stripped.replace("[dim]", "").replace("[/]", "")))
        else:
            description.append(_plain(line))
    return "\n".join(description).strip(), "\n".join(e for e in examples if e)


def command_section(path: str, command: Command, level: int) -> list[str]:
    """Return the Markdown for one runnable command."""
    arguments = [p for p in command.params if not _is_option(p)]
    usage = " ".join(
        ["acli-py", path, *(f"[{a.human_readable_name.upper()}]" if not a.required
                       else a.human_readable_name.upper() for a in arguments), "[OPTIONS]"]
    )  # fmt: skip
    description, examples = _help(command)
    lines = [f"{'#' * level} `acli-py {path}`", "", description, "", "```text", usage, "```", ""]
    if examples:
        lines += ["```sh", examples, "```", ""]
    lines += ["| Option | Default | Description |", "|---|---|---|"]
    for param in command.params:
        if _is_option(param) and param.hidden:
            continue
        if _is_option(param):
            names = sorted(param.opts, key=len) + param.secondary_opts
            metavar = _metavar(param)
            spelled = ", ".join(f"`{n}`" for n in names) + (f" `{metavar}`" if metavar else "")
            help_text = _plain(param.help)
        else:
            spelled = f"`{param.human_readable_name.upper()}`"
            help_text = _plain(getattr(param, "help", ""))
        lines.append(f"| {_cell(spelled)} | {_default(param)} | {_cell(help_text)} |")
    lines += ["", ""]
    return lines


def group_page(name: str, group: Command) -> str:
    """Return the page for a top-level group (or a single top-level command)."""
    lines = [HEADER, "", f"# acli-py {name}", ""]
    if not hasattr(group, "commands"):
        return "\n".join(lines + command_section(name, group, 2)).rstrip() + "\n"
    lines += [_plain(group.help), "", ""]

    def walk(command: Command, path: list[str]) -> None:
        for sub_name, sub in command.commands.items():
            if sub.hidden:
                continue
            if hasattr(sub, "commands"):
                lines.extend(
                    [f"## `acli-py {' '.join([*path, sub_name])}`", "", _plain(sub.help), "", ""]
                )
                walk(sub, [*path, sub_name])
            else:
                lines.extend(
                    command_section(" ".join([*path, sub_name]), sub, 3 if len(path) > 1 else 2)
                )

    walk(group, [name])
    return "\n".join(lines).rstrip() + "\n"


def pages() -> dict[Path, str]:
    """Return every generated page, keyed by its path."""
    root: Command = typer.main.get_command(app)
    result: dict[Path, str] = {}
    toc: list[str] = []
    commands = root.commands.items()
    # Groups first, in the order `acli-py --help` shows them; single commands (api) last.
    for name, command in sorted(commands, key=lambda item: not hasattr(item[1], "commands")):
        if command.hidden:
            continue
        result[PAGES / f"{name}.md"] = group_page(name, command)
        toc.append(name)
    index = [
        HEADER,
        "",
        "# Commands",
        "",
        "Every command, generated from `acli-py --help`. Global options go before the command:",
        "",
        "| Option | Description |",
        "|---|---|",
    ]
    for param in root.params:
        if (
            _is_option(param)
            and not param.hidden
            and param.name not in ("install_completion", "show_completion")
        ):
            names = ", ".join(f"`{n}`" for n in sorted(param.opts, key=len))
            index.append(f"| {names} | {_cell(_plain(param.help))} |")
    index += ["", "```{toctree}", ":maxdepth: 2", "", *toc, "```", ""]
    result[PAGES / "index.md"] = "\n".join(index)
    return result


def main(argv: list[str]) -> int:
    """Write the pages, or with --check report the stale ones."""
    check = "--check" in argv
    stale = []
    wanted = pages()
    for path, text in wanted.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != text:
            stale.append(path)
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding="utf-8")
    extra = [p for p in PAGES.glob("*.md") if p not in wanted]
    for path in extra:
        stale.append(path)
        if not check:
            path.unlink()
    for path in stale:
        print(f"{'stale' if check else 'wrote'}: {path.relative_to(ROOT)}")
    return 1 if check and stale else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
